[package]
name = "day-06"
version = "0.1.0"
edition = "2021"

[dependencies]
indicatif = { version = "0.17.9", features = ["rayon"] }
rayon = "1.10.0"
shared = { path = "../shared/" }

[lints]
workspace = true
